version: '3.4'

services:
  showcase.todolist:
    image: ${DOCKER_REGISTRY-}showcasetodolist
    container_name: showcase.api
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
      showcase.database:
        condition: service_healthy
  showcase.database:
    image: postgres:16.2-alpine
    restart: always
    container_name: showcase.database    
    environment:
     - POSTGRES_DB=Showcase
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/showcase-database:/var/lib/postgresql/data
    ports:
     - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready -d Showcase -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


