version: '3.4'

services:
  showcase.todolist:
    image: ${DOCKER_REGISTRY-}showcasetodolist
    container_name: showcase.api
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
  showcase.database:
    image: postgres:16.2
    container_name: showcase.database
    environment:
     - POSTGRES_DB=Showcase
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/showcase-database:/var/lib/postgresql/data
    ports:
     - 5432:5432



